# remove all object files to force recompilation
rm -rf src/core/*.o

# cd pyodide

# compile core (C/C++) files
emcc -o src/core/main.o -c src/core/main.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/docstring.o -c src/core/docstring.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/error_handling.o -c src/core/error_handling.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/hiwire.o -c src/core/hiwire.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/_pyodide_core.o -c src/core/_pyodide_core.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/js2python.o -c src/core/js2python.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/jsproxy.o -c src/core/jsproxy.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/pyproxy.o -c src/core/pyproxy.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/python2js_buffer.o -c src/core/python2js_buffer.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
emcc -o src/core/python2js.o -c src/core/python2js.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/include/python3.11 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/


# build pyodide.asm.js
em++ -pedantic -Wall -Wextra -o dist/pyodide.asm.js dist/libpyodide.a src/core/main.o -O2 -g0  -L/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/lib/ -s WASM_BIGINT -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s MAIN_MODULE=1 -s MODULARIZE=1 -s LZ4=1 -s EXPORT_NAME="'_createPyodideModule'" -s EXPORT_EXCEPTION_HANDLING_HELPERS -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -sEXPORTED_RUNTIME_METHODS='stackAlloc,stackRestore,stackSave' -s DEMANGLE_SUPPORT=1 -s USE_ZLIB -s USE_BZIP2 -s FORCE_FILESYSTEM=1 -s TOTAL_MEMORY=20971520 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_ALL=1 -s POLYFILL -s MIN_SAFARI_VERSION=140000 -s STACK_SIZE=5MB -s AUTO_JS_LIBRARIES=0 -s AUTO_NATIVE_LIBRARIES=0 -s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0 -lpython3.11 -lffi -lstdc++ -lidbfs.js -lnodefs.js -lproxyfs.js -lworkerfs.js -lwebsocket.js -leventloop.js -lGL -legl.js -lwebgl.js -lhtml5_webgl.js -sGL_WORKAROUND_SAFARI_GETCONTEXT_BUG=0

# em++ -pedantic -Wall -Wextra -o dist/pyodide.asm.js dist/libpyodide.a src/core/main.o -O2 -g0  -L/home/pradeep/projects/pyodide-with-pyqt5/pyodide/cpython/installs/python-3.11.3/lib/ -s WASM_BIGINT -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s MAIN_MODULE=1 -s MODULARIZE=1 -s LZ4=1 -s EXPORT_NAME="'_createPyodideModule'" -s EXPORT_EXCEPTION_HANDLING_HELPERS -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -sEXPORTED_RUNTIME_METHODS='stackAlloc,stackRestore,stackSave' -sEXPORTED_FUNCTIONS=_PyInit_QtCore -s DEMANGLE_SUPPORT=1 -s USE_ZLIB -s USE_BZIP2 -s FORCE_FILESYSTEM=1 -s TOTAL_MEMORY=20971520 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_ALL=1 -s POLYFILL -s MIN_SAFARI_VERSION=140000 -s STACK_SIZE=5MB -s AUTO_JS_LIBRARIES=0 -s AUTO_NATIVE_LIBRARIES=0 -s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0 -lpython3.11 /home/pradeep/projects/pyodide-with-pyqt5/pyqt6-wasm-target/PyQt6/QtCore.abi3.a -lffi -lstdc++ -lidbfs.js -lnodefs.js -lproxyfs.js -lworkerfs.js -lwebsocket.js -leventloop.js -lGL -legl.js -lwebgl.js -lhtml5_webgl.js -sGL_WORKAROUND_SAFARI_GETCONTEXT_BUG=0

if [[ -n ${PYODIDE_SOURCEMAP+x} ]] || [[ -n ${PYODIDE_SYMBOLS+x} ]] || [[ -n ${PYODIDE_DEBUG_JS+x} ]]; then \
	cd dist && npx prettier -w pyodide.asm.js ; \
fi

sed -i -E 's/var __Z[^;]*;//g' dist/pyodide.asm.js
sed -i '1i "use strict";' dist/pyodide.asm.js
# Remove last 4 lines of pyodide.asm.js, see issue #2282
# Hopefully we will remove this after emscripten fixes it, upstream issue
# emscripten-core/emscripten#16518
# Sed nonsense from https://stackoverflow.com/a/13383331
sed -i -n -e :a -e '1,4!{P;N;D;};N;ba' dist/pyodide.asm.js
echo "globalThis._createPyodideModule = _createPyodideModule;" >> dist/pyodide.asm.js